"use client";
import { useEffect, useRef } from "react";
import type { DomainVizProps } from "./registry";
const ACCENT = "#22d3ee";

export default function BiologyComparison({ locale }: DomainVizProps) {
  const ref = useRef<HTMLDivElement>(null); const isZh = locale === "zh";
  useEffect(() => { if (typeof window === "undefined") return; import("gsap").then(({ default: g }) => { const ctx = g.context(() => { g.fromTo(".cc", { opacity: 0, y: 24 }, { opacity: 1, y: 0, duration: 0.5, stagger: 0.12, ease: "power2.out" }); }, ref.current!); return () => ctx.revert(); }); }, []);
  const items = [
    { title: isZh ? "DNA双螺旋 ↔ 阴阳缠绕" : "DNA Double Helix ↔ Yin-Yang Entwinement", viz: (<svg width="200" height="120" viewBox="0 0 200 120" className="mx-auto"><path d="M30,20 Q100,70 170,20" fill="none" stroke={ACCENT} strokeWidth="2" opacity="0.7"/><path d="M30,100 Q100,50 170,100" fill="none" stroke={ACCENT} strokeWidth="2" opacity="0.4"/><line x1="45" y1="38" x2="45" y2="90" stroke="#52525b" strokeWidth="0.3" opacity="0.5"/><line x1="80" y1="55" x2="80" y2="55" stroke="#52525b" strokeWidth="5" opacity="0.3"/><line x1="115" y1="55" x2="115" y2="55" stroke="#52525b" strokeWidth="5" opacity="0.3"/><line x1="150" y1="35" x2="150" y2="95" stroke="#52525b" strokeWidth="0.3" opacity="0.5"/><text x="30" y="14" textAnchor="middle" fontSize="7" fill={ACCENT} opacity="0.5">A···T</text><text x="170" y="14" textAnchor="middle" fontSize="7" fill={ACCENT} opacity="0.5">G···C</text><text x="100" y="115" textAnchor="middle" fontSize="9" fill="#71717a">{isZh?"每链含另一链的全部信息" : "Each strand = other's template"}</text></svg>), note: isZh ? "DNA两条互补链A-T/G-C互相缠绕——每一条都是另一条的'反版'，正如太极图中阴中含阳、阳中含阴。互补性不只是一个比喻，而是生命最核心的物理结构。" : "Two complementary strands — each is the 'negative' of the other, just as yin contains yang. Complementarity is not metaphor but life's most fundamental physical structure." },
    { title: isZh ? "表观遗传 ↔ 基因(阴) × 环境(阳)" : "Epigenetics ↔ Gene (Yin) × Environment (Yang)", viz: (<div className="flex items-center justify-center gap-4 py-3"><div className="text-center"><svg width="70" height="70" viewBox="0 0 70 70"><circle cx="35" cy="35" r="30" fill="none" stroke={ACCENT} strokeWidth="0.5" opacity="0.3"/><text x="35" y="38" textAnchor="middle" fontSize="8" fill={ACCENT}>{isZh?"相同DNA":"Same DNA"}</text></svg><p className="text-[8px] text-zinc-500 mt-1">{isZh?"基因=乐谱":"Gene=score"}</p></div><span className="text-zinc-600 text-lg">+</span><div className="text-center"><svg width="70" height="70" viewBox="0 0 70 70"><circle cx="35" cy="35" r="30" fill="none" stroke="#fbbf24" strokeWidth="0.5" opacity="0.4"/><text x="35" y="38" textAnchor="middle" fontSize="8" fill="#fbbf24">{isZh?"不同环境":"Diff Env"}</text></svg><p className="text-[8px] text-zinc-500 mt-1">{isZh?"环境=演奏":"Env=perform"}</p></div><span className="text-zinc-600">→</span><div className="text-center"><svg width="70" height="70" viewBox="0 0 70 70"><circle cx="25" cy="30" r="12" fill={`${ACCENT}15`} stroke={ACCENT} strokeWidth="0.6"/><circle cx="45" cy="30" r="12" fill={`${ACCENT}05`} stroke={ACCENT} strokeWidth="0.6" opacity="0.4"/></svg><p className="text-[8px] text-zinc-500 mt-1">{isZh?"表达不同":"Diff expr"}</p></div></div>), note: isZh ? "同卵双胞胎相同DNA可产生截然不同的表达结果。生命是基因（阴）与环境（阳）的持续对话——基因不是命运，是互动的起点。" : "Identical twins' same DNA produces different outcomes. Life is continuous gene (yin) and environment (yang) dialogue — genes are not destiny but the starting point of interaction." },
    { title: isZh ? "免疫系统 ↔ 阴阳防御" : "Immune System ↔ Yin-Yang Defense", viz: (<svg width="200" height="100" viewBox="0 0 200 100" className="mx-auto"><rect x="10" y="10" width="85" height="80" rx="10" fill={`${ACCENT}08`} stroke={ACCENT} strokeWidth="0.5" opacity="0.4"/><text x="52" y="45" textAnchor="middle" fontSize="8" fill={ACCENT}>{isZh?"先天免疫" : "Innate"}</text><text x="52" y="58" textAnchor="middle" fontSize="7" fill={ACCENT} opacity="0.5">{isZh?"(阴·快速·古老)" : "(Yin·Fast·Ancient)"}</text><rect x="105" y="10" width="85" height="80" rx="10" fill={`${ACCENT}12`} stroke={ACCENT} strokeWidth="0.8" opacity="0.7"/><text x="147" y="45" textAnchor="middle" fontSize="8" fill={ACCENT}>{isZh?"适应性免疫":"Adaptive"}</text><text x="147" y="58" textAnchor="middle" fontSize="7" fill={ACCENT} opacity="0.5">{isZh?"(阳·精准·记忆)":"(Yang·Precise)"}</text><text x="100" y="98" textAnchor="middle" fontSize="7" fill="#71717a">{isZh?"平衡 = 健康 | 失衡 = 疾病":"Balance = Health | Imbalance = Disease"}</text></svg>), note: isZh ? "先天免疫（阴——快速非特异古老的'默认防线'）与适应性免疫（阳——精准特异记忆性的'定制武器'）——健康取决于两者的动态平衡。" : "Innate (yin — fast, ancient, non-specific) and adaptive (yang — precise, memory-based) — health depends on their dynamic balance." },
  ];
  return (<div ref={ref}><div className="flex items-center gap-3 mb-6"><span className="w-1.5 h-1.5 rounded-full" style={{backgroundColor:ACCENT}}/><h2 className="text-sm font-semibold uppercase tracking-[0.15em] text-zinc-400">{isZh?"可视化对照":"Visual Comparison"}</h2></div><div className="space-y-4">{items.map((item,i)=>(<div key={i} className="cc rounded-2xl p-[1px] bg-white/[0.02] hover:bg-white/[0.04] transition-colors duration-500"><div className="rounded-[calc(1.5rem-1px)] p-5 bg-[#0c0c0f] border border-white/[0.03]"><h4 className="text-xs font-semibold text-zinc-300 mb-3 text-center">{item.title}</h4>{item.viz}<p className="text-center text-[11px] text-zinc-600 mt-3 leading-relaxed">{item.note}</p></div></div>))}</div></div>);
}
