"use client";
import { useEffect, useRef } from "react";
import type { DomainVizProps } from "./registry";
const ACCENT = "#f97316";

export default function ComputerScienceComparison({ locale }: DomainVizProps) {
  const ref = useRef<HTMLDivElement>(null); const isZh = locale === "zh";
  useEffect(() => { if (typeof window === "undefined") return; import("gsap").then(({ default: g }) => { const ctx = g.context(() => { g.fromTo(".cc", { opacity: 0, y: 24 }, { opacity: 1, y: 0, duration: 0.5, stagger: 0.12, ease: "power2.out" }); }, ref.current!); return () => ctx.revert(); }); }, []);
  const items = [
    { title: isZh ? "布尔代数 ↔ 阴阳逻辑运算" : "Boolean Algebra ↔ Yin-Yang Logic", viz: (<div className="flex items-center justify-center gap-4 py-3"><div className="text-center"><span className="text-lg font-bold" style={{color:ACCENT}}>AND</span><p className="text-[8px] text-zinc-500">{isZh?"阴阳相交":"Intersect"}</p></div><div className="text-center"><span className="text-lg font-bold" style={{color:ACCENT,opacity:0.7}}>OR</span><p className="text-[8px] text-zinc-500">{isZh?"阴阳相合":"Union"}</p></div><div className="text-center"><span className="text-lg font-bold" style={{color:ACCENT,opacity:0.5}}>NOT</span><p className="text-[8px] text-zinc-500">{isZh?"阴阳互转":"Transform"}</p></div><span className="text-zinc-600">=</span><span className="text-[10px] text-zinc-400">{isZh?"一切计算的\n原子" : "Atom of all\ncomputation"}</span></div>), note: isZh ? "AND（阴阳相交始有物）、OR（阴阳相合而生）、NOT（阴阳互转）——三种基本逻辑运算精确映射了阴阳的三种关系，构成了所有计算机芯片的基础。" : "AND, OR, NOT — the three basic logic operations precisely map to yin-yang's three fundamental relationships, forming the foundation of all computer chips." },
    { title: isZh ? "德·摩根定律 ↔ 阴阳互化" : "De Morgan's Laws ↔ Yin-Yang Transformation", viz: (<div className="flex items-center justify-center gap-2 py-3 text-[10px] font-mono text-zinc-400 flex-wrap"><span>¬(A∧B)</span><span className="text-zinc-600">=</span><span style={{color:ACCENT}}>¬A ∨ ¬B</span><span className="text-zinc-600 mx-2">|</span><span>¬(A∨B)</span><span className="text-zinc-600">=</span><span style={{color:ACCENT}}>¬A ∧ ¬B</span><p className="w-full text-center text-[8px] text-zinc-500 mt-1">{isZh?"AND和OR通过NOT互相转化——正如阴阳通过旋转互变" : "AND and OR transform through NOT — as yin-yang through rotation"}</p></div>), note: isZh ? "AND和OR通过NOT互相转化，正如太极图中阴与阳通过旋转互变。这是逻辑世界中最精确、最优雅的阴阳互化定律。" : "AND and OR transform into each other through NOT, just as yin and yang transform through rotation. Logic's most precise and elegant yin-yang transformation law." },
    { title: isZh ? "P vs NP ↔ 计算的根本不对称" : "P vs NP ↔ Computational Asymmetry", viz: (<svg width="200" height="80" viewBox="0 0 200 80" className="mx-auto"><rect x="10" y="10" width="80" height="60" rx="8" fill={`${ACCENT}15`} stroke={ACCENT} strokeWidth="0.8"/><text x="50" y="38" textAnchor="middle" fontSize="8" fill={ACCENT}>{isZh?"验证解" : "Verify"}</text><text x="50" y="50" textAnchor="middle" fontSize="7" fill={ACCENT} opacity="0.5">{isZh?"(阳·判断·快)" : "(Yang·Fast)"}</text><rect x="110" y="10" width="80" height="60" rx="8" fill={`${ACCENT}06`} stroke={ACCENT} strokeWidth="0.5" opacity="0.4"/><text x="150" y="38" textAnchor="middle" fontSize="8" fill={ACCENT} opacity="0.6">{isZh?"找到解" : "Find"}</text><text x="150" y="50" textAnchor="middle" fontSize="7" fill={ACCENT} opacity="0.3">{isZh?"(阴·创造·慢?)":"(Yin·Slow?)"}</text><text x="100" y="28" textAnchor="middle" fontSize="14" fill={ACCENT} opacity="0.4">?</text></svg>), note: isZh ? "如果P≠NP，'判断'永远比'创造'容易——这是计算宇宙中最深刻的阴阳不对称性。太极的核心洞见：不对等驱动了一切运动和变化。" : "If P≠NP, 'judging' is forever easier than 'creating' — the deepest yin-yang asymmetry in computation. Taiji's core insight: imbalance drives all motion and change." },
  ];
  return (<div ref={ref}><div className="flex items-center gap-3 mb-6"><span className="w-1.5 h-1.5 rounded-full" style={{backgroundColor:ACCENT}}/><h2 className="text-sm font-semibold uppercase tracking-[0.15em] text-zinc-400">{isZh?"可视化对照":"Visual Comparison"}</h2></div><div className="space-y-4">{items.map((item,i)=>(<div key={i} className="cc rounded-2xl p-[1px] bg-white/[0.02] hover:bg-white/[0.04] transition-colors duration-500"><div className="rounded-[calc(1.5rem-1px)] p-5 bg-[#0c0c0f] border border-white/[0.03]"><h4 className="text-xs font-semibold text-zinc-300 mb-3 text-center">{item.title}</h4>{item.viz}<p className="text-center text-[11px] text-zinc-600 mt-3 leading-relaxed">{item.note}</p></div></div>))}</div></div>);
}
