"use client";
import { useEffect, useRef } from "react";
import type { DomainVizProps } from "./registry";
const ACCENT = "#818cf8";

export default function CosmologyComparison({ locale }: DomainVizProps) {
  const ref = useRef<HTMLDivElement>(null); const isZh = locale === "zh";
  useEffect(() => { if (typeof window === "undefined") return; import("gsap").then(({ default: g }) => { const ctx = g.context(() => { g.fromTo(".cc", { opacity: 0, y: 24 }, { opacity: 1, y: 0, duration: 0.5, stagger: 0.12, ease: "power2.out" }); }, ref.current!); return () => ctx.revert(); }); }, []);
  const items = [
    { title: isZh ? "无极生太极 ↔ 大爆炸" : "Wuji→Taiji ↔ Big Bang", viz: (<svg width="200" height="120" viewBox="0 0 200 120" className="mx-auto"><circle cx="55" cy="60" r="8" fill={ACCENT} opacity="0.9"><animate attributeName="r" values="8;45" dur="3s" repeatCount="indefinite"/><animate attributeName="opacity" values="0.9;0.05" dur="3s" repeatCount="indefinite"/></circle><text x="55" y="64" textAnchor="middle" fontSize="8" fill={ACCENT}>{isZh?"奇点":"Singularity"}</text><text x="100" y="40" fontSize="18" fill={ACCENT} opacity="0.4">→</text><circle cx="155" cy="60" r="38" fill="none" stroke={ACCENT} strokeWidth="0.6" opacity="0.4" /><path d="M155,22 A38,38 0 0,1 155,98 A19,19 0 0,0 155,60 A19,19 0 0,1 155,22 Z" fill={`${ACCENT}08`} /><circle cx="155" cy="41" r="3" fill={ACCENT} opacity="0.3"/><circle cx="155" cy="79" r="3" fill="#18181b"/><text x="155" y="108" textAnchor="middle" fontSize="8" fill={ACCENT} opacity="0.5">{isZh?"太极宇宙":"Taiji Cosmos"}</text></svg>), note: isZh ? "138亿年前宇宙从奇点中诞生——从'无极'的无限致密状态中爆发出了我们的'太极'宇宙。暴涨(inflation)是从统一到分化的第一推动。" : "13.8B years ago, the universe was born from a singularity — from 'Wuji's infinitely dense state burst our 'Taiji' cosmos. Inflation was the first push from unity to differentiation." },
    { title: isZh ? "暗物质/暗能量 ↔ 不可见的'阴'" : "Dark Matter/Energy ↔ Invisible Yin", viz: (<svg width="200" height="100" viewBox="0 0 200 100" className="mx-auto"><rect x="10" y="15" width="50" height="70" rx="8" fill={ACCENT} opacity="0.15" stroke={ACCENT} strokeWidth="0.5"/><text x="35" y="55" textAnchor="middle" fontSize="7" fill={ACCENT}>{isZh?"暗能量\n68%":"Dark Energy\n68%"}</text><rect x="65" y="25" width="40" height="60" rx="8" fill={ACCENT} opacity="0.25" stroke={ACCENT} strokeWidth="0.5"/><text x="85" y="55" textAnchor="middle" fontSize="7" fill={ACCENT}>{isZh?"暗物质\n27%":"Dark Matter\n27%"}</text><rect x="110" y="40" width="15" height="45" rx="8" fill="#f4f4f5" opacity="0.08" stroke="#52525b" strokeWidth="0.5"/><text x="117" y="80" textAnchor="middle" fontSize="6" fill="#71717a">{isZh?"可见\n5%":"Visible\n5%"}</text><text x="100" y="15" textAnchor="middle" fontSize="8" fill="#71717a">{isZh?"宇宙质能组成" : "Cosmic Energy Budget"}</text></svg>), note: isZh ? "可见物质仅5%，暗物质27%，暗能量68%——宇宙绝大部分是'阴'（不可见的），正如太极图中可见的图案只是表面。" : "Visible: 5%, dark matter: 27%, dark energy: 68% — overwhelmingly 'yin' (invisible), just as the Taiji's visible pattern is only the surface." },
    { title: isZh ? "CP破缺 ↔ 阴阳不对称" : "CP Violation ↔ Yin-Yang Asymmetry", viz: (<div className="flex items-center justify-center gap-3 py-3"><svg width="80" height="60" viewBox="0 0 80 60"><circle cx="25" cy="30" r="15" fill={`${ACCENT}15`} stroke={ACCENT} strokeWidth="0.8"/><text x="25" y="33" textAnchor="middle" fontSize="8" fill={ACCENT}>{isZh?"物质" : "Matter"}</text><text x="25" y="18" textAnchor="middle" fontSize="9" fill={ACCENT} fontWeight="bold">10⁹+1</text><circle cx="55" cy="30" r="15" fill={`${ACCENT}05`} stroke={ACCENT} strokeWidth="0.8" opacity="0.4"/><text x="55" y="33" textAnchor="middle" fontSize="8" fill={ACCENT} opacity="0.5">{isZh?"反物质" : "Anti"}</text><text x="55" y="18" textAnchor="middle" fontSize="9" fill={ACCENT} opacity="0.5">10⁹</text></svg><span className="text-zinc-600 text-xs">→</span><span className="text-xs text-zinc-300">{isZh?"十亿分之一的\n不对等 = 宇宙存在" : "One-in-a-billion\nimbalance = existence"}</span></div>), note: isZh ? "每10⁹对粒子-反粒子中物质多1个——正是这十亿分之一的'阴阳不对等'创造了可见宇宙。纯对称=虚无，不对等=存在。" : "1 extra matter particle per 10⁹ pairs — this one-in-a-billion 'yin-yang imbalance' created the visible universe. Perfect symmetry = nothingness; imbalance = existence." },
  ];
  return (<div ref={ref}><div className="flex items-center gap-3 mb-6"><span className="w-1.5 h-1.5 rounded-full" style={{backgroundColor:ACCENT}}/><h2 className="text-sm font-semibold uppercase tracking-[0.15em] text-zinc-400">{isZh?"可视化对照":"Visual Comparison"}</h2></div><div className="space-y-4">{items.map((item,i)=>(<div key={i} className="cc rounded-2xl p-[1px] bg-white/[0.02] hover:bg-white/[0.04] transition-colors duration-500"><div className="rounded-[calc(1.5rem-1px)] p-5 bg-[#0c0c0f] border border-white/[0.03]"><h4 className="text-xs font-semibold text-zinc-300 mb-3 text-center">{item.title}</h4>{item.viz}<p className="text-center text-[11px] text-zinc-600 mt-3 leading-relaxed">{item.note}</p></div></div>))}</div></div>);
}
