"use client";
import { useEffect, useRef } from "react";
import type { DomainVizProps } from "./registry";
const ACCENT = "#e879f9";

export default function PsychologyComparison({ locale }: DomainVizProps) {
  const ref = useRef<HTMLDivElement>(null); const isZh = locale === "zh";
  useEffect(() => { if (typeof window === "undefined") return; import("gsap").then(({ default: g }) => { const ctx = g.context(() => { g.fromTo(".cc", { opacity: 0, y: 24 }, { opacity: 1, y: 0, duration: 0.5, stagger: 0.12, ease: "power2.out" }); }, ref.current!); return () => ctx.revert(); }); }, []);
  const items = [
    { title: isZh ? "意识与无意识 ↔ 阳与阴" : "Conscious & Unconscious ↔ Yang & Yin", viz: (<svg width="160" height="120" viewBox="0 0 160 120" className="mx-auto"><circle cx="55" cy="60" r="30" fill="none" stroke={ACCENT} strokeWidth="0.8" opacity="0.6"/><text x="55" y="64" textAnchor="middle" fontSize="10" fill={ACCENT}>{isZh?"意识":"Conscious"}</text><text x="55" y="78" textAnchor="middle" fontSize="7" fill={ACCENT} opacity="0.5">{isZh?"(阳·理性·光明)":"(Yang·Rational)"}</text><circle cx="105" cy="60" r="30" fill="none" stroke={ACCENT} strokeWidth="0.6" opacity="0.3" strokeDasharray="3 3"/><text x="105" y="64" textAnchor="middle" fontSize="10" fill={ACCENT} opacity="0.5">{isZh?"无意识" : "Unconscious"}</text><text x="105" y="78" textAnchor="middle" fontSize="7" fill={ACCENT} opacity="0.3">{isZh?"(阴·直觉·幽暗)":"(Yin·Intuitive)"}</text><path d="M85,50 Q95,30 105,50" fill="none" stroke={ACCENT} strokeWidth="0.5" opacity="0.3"/><text x="80" y="100" textAnchor="middle" fontSize="7" fill="#71717a">{isZh?"个性化 = 阴阳整合" : "Individuation = Integration"}</text></svg>), note: isZh ? "荣格的心理模型是一幅精妙的太极图：意识（阳——理性光明）与无意识（阴——直觉幽暗）需要通过'个性化'过程整合为完整的自我。" : "Jung's model is an exquisite Taiji: consciousness (yang) and unconscious (yin) integrate through 'Individuation' into a complete self." },
    { title: isZh ? "共时性 ↔ 万物感应" : "Synchronicity ↔ Universal Resonance", viz: (<div className="flex items-center justify-center gap-4 py-4"><div className="text-center"><svg width="60" height="60" viewBox="0 0 60 60"><circle cx="30" cy="30" r="25" fill="none" stroke={ACCENT} strokeWidth="0.5" opacity="0.3"/><circle cx="30" cy="30" r="5" fill={ACCENT} opacity="0.4"><animate attributeName="r" values="5;15" dur="2s" repeatCount="indefinite"/><animate attributeName="opacity" values="0.4;0" dur="2s" repeatCount="indefinite"/></circle></svg><p className="text-[8px] text-zinc-500 mt-1">{isZh?"内心事件":"Inner event"}</p></div><span className="text-zinc-600">~</span><span className="text-[10px] text-zinc-400">{isZh?"有意义的\n巧合":"Meaningful\ncoincidence"}</span><span className="text-zinc-600">~</span><div className="text-center"><svg width="60" height="60" viewBox="0 0 60 60"><circle cx="30" cy="30" r="25" fill="none" stroke={ACCENT} strokeWidth="0.5" opacity="0.3"/><circle cx="30" cy="30" r="5" fill={ACCENT} opacity="0.4"><animate attributeName="r" values="5;15" dur="2s" begin="1s" repeatCount="indefinite"/><animate attributeName="opacity" values="0.4;0" dur="2s" begin="1s" repeatCount="indefinite"/></circle></svg><p className="text-[8px] text-zinc-500 mt-1">{isZh?"外部事件":"Outer event"}</p></div></div>), note: isZh ? "荣格发现两个无因果关系的事件可以通过意义共振相连——不是A导致B，而是A和B在更大的意义网络中互相感应，正如太极图中的阴阳共振。" : "Jung found acausally connected events resonating through meaning — not A causing B, but A and B resonating in a larger meaning network, like yin-yang resonance in the Taiji." },
    { title: isZh ? "正念 ↔ S曲线的觉察空间" : "Mindfulness ↔ S-Curve Awareness", viz: (<svg width="180" height="80" viewBox="0 0 180 80" className="mx-auto"><line x1="10" y1="60" x2="170" y2="60" stroke="#3f3f46" strokeWidth="0.5"/><text x="10" y="72" textAnchor="middle" fontSize="7" fill="#71717a">{isZh?"抓住(阳)" : "Grasp (Yang)"}</text><text x="170" y="72" textAnchor="middle" fontSize="7" fill="#71717a">{isZh?"推开(阴)" : "Reject (Yin)"}</text><circle cx="90" cy="40" r="18" fill="none" stroke={ACCENT} strokeWidth="1" opacity="0.5"/><text x="90" y="43" textAnchor="middle" fontSize="8" fill={ACCENT}>{isZh?"觉察" : "Aware"}</text><line x1="90" y1="58" x2="90" y2="60" stroke={ACCENT} strokeWidth="1"/></svg>), note: isZh ? "正念教我们观察而不评判——不抓住念头（阳的执着）也不推开它们（阴的排斥），在S曲线的中间态找到平衡。8周训练即可改变大脑结构。" : "Mindfulness teaches observing without judging — neither grasping (yang) nor rejecting (yin). 8 weeks of training changes brain structure." },
  ];
  return (<div ref={ref}><div className="flex items-center gap-3 mb-6"><span className="w-1.5 h-1.5 rounded-full" style={{backgroundColor:ACCENT}}/><h2 className="text-sm font-semibold uppercase tracking-[0.15em] text-zinc-400">{isZh?"可视化对照":"Visual Comparison"}</h2></div><div className="space-y-4">{items.map((item,i)=>(<div key={i} className="cc rounded-2xl p-[1px] bg-white/[0.02] hover:bg-white/[0.04] transition-colors duration-500"><div className="rounded-[calc(1.5rem-1px)] p-5 bg-[#0c0c0f] border border-white/[0.03]"><h4 className="text-xs font-semibold text-zinc-300 mb-3 text-center">{item.title}</h4>{item.viz}<p className="text-center text-[11px] text-zinc-600 mt-3 leading-relaxed">{item.note}</p></div></div>))}</div></div>);
}
